Repository TeamRichardStallman/dv-front, pull requests merged in 2024-12, with the labels that each got.

#38 [DV-173] 유저폼 리팩토링
  .env.sample
  next.config.ts
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/app/(user)/auth/page.tsx
  src/app/(user)/layout.tsx
  src/app/(user)/signup/page.tsx
  src/app/api/s3/getFile/route.ts
  src/app/page.tsx
  src/components/header.tsx
  src/components/user-form.tsx
  src/utils/firebaseConfig.ts
  src/utils/format.ts
  src/utils/requestFcmToken.js
  src/utils/setFcmKey.js
Labels: refactor, feature

#39 [DV-194] 쿠폰으로 이용권 결제 안되던 문제 해결
  src/app/mypage/voucher/page.tsx
Labels: bug, refactor

#41 [DV-196] 면접 setup 과정 중 실전/모의 단계와 음성/채팅 단계에서 이용권 확인 후 모달 띄우기
  src/app/interview/page.tsx
  src/app/mypage/voucher/page.tsx
  src/components/interview/step/method-step.tsx
  src/components/payment-modal.tsx
Labels: refactor, feature

#40 feat : google analytics 적용 및 정보 수정
  public/firebase-messaging-sw.js
  src/utils/firebaseConfig.ts
Labels: feature

#42 Dv 198 fe text interview api connection
  src/app/(user)/auth/page.tsx
  src/app/(user)/signup/page.tsx
  src/app/interview/feedback/[interviewId]/page.tsx
  src/app/interview/ongoing/[interviewId]/page.tsx
  src/app/interview/ongoing/prepare/page.tsx
  src/app/interview/page.tsx
  src/app/mypage/coupon/page.tsx
  src/app/mypage/edit/page.tsx
  src/app/mypage/feedback/[interviewId]/page.tsx
  src/app/mypage/feedback/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/payment-history/page.tsx
  src/app/mypage/voucher/page.tsx
  src/components/interview/interview-feedback-detail.tsx
  src/components/interview/setup-funnel.tsx
  src/components/interview/step/check-info-step.tsx
  src/components/interview/step/method-step.tsx
  src/components/payment-modal.tsx
  src/stores/useQuestionRequest.ts
  src/types/coupon.d.ts
  src/types/interview.d.ts
  src/types/types.d.ts
  src/types/user.d.ts
Labels: feature

#43 [DV-200] 음성면접 시작시 질문 생성하는 동안 음성과 오디오 체크하기
  public/audiotest.mp3
  src/app/interview/ongoing/prepare/page.tsx
Labels: refactor, feature

#44 [DV-201] S3에 음성파일 업로드 되도록 하기
  src/app/interview/ongoing/page.tsx
Labels: feature

#45 [DV-205] 채팅면접에서는 마이크 허용창 안뜨도록 하기
  src/app/interview/ongoing/prepare/page.tsx
Labels: bug

#46 [DV-204] username 중복 검사를 안했거나 중복일 경우에는 회원가입 못하게 하기
  src/components/user-form.tsx
Labels: feature

#47 [DV-206] 로그인이 안되었을 경우 로그인 페이지로 redirect
  src/app/page.tsx
  src/components/header.tsx
Labels: feature

#48 Dv 202 fe user update and payment voice implement
  package.json
  src/app/interview/ongoing/[interviewId]/page.tsx
  src/app/interview/ongoing/page.tsx
  src/app/interview/ongoing/prepare/page.tsx
  src/components/interview/step/check-info-step.tsx
  src/types/mic-recorder-to-mp3.d.ts
Labels: feature

#50 [DV-215] lint 이슈 해결
  package-lock.json
  src/app/interview/feedback/[interviewId]/page.tsx
  src/app/interview/ongoing/[interviewId]/page.tsx
  src/app/interview/ongoing/page.tsx
  src/app/mypage/feedback/[interviewId]/page.tsx
  src/components/interview/step/check-info-step.tsx
  src/components/user-form.tsx
Labels: bug, refactor

#51 [DV-217] 마이페이지 자잘한 이슈 해결
  src/components/user-form.tsx
Labels: refactor, feature

#53 [DV-223] SNS UI 구현
  next.config.ts
  public/icons/feedback-share-icon.svg
  public/icons/icon-plus-circle.png
  public/icons/icon-plus-circle.svg
  public/icons/interview-share-icon.svg
  public/icons/write-icon.svg
  src/app/community/layout.tsx
  src/app/community/page.tsx
  src/components/post-modal.tsx
  src/data/postData.ts
Labels: feature

#54 Dv 209 fe audio presignedurl request
  src/app/interview/ongoing/[interviewId]/page.tsx
  src/types/types.d.ts
Labels: feature

#55 [DV-231] 음성 면접 진행 과정 구현
  package-lock.json
  package.json
  src/app/interview/ongoing/[interviewId]/page.tsx
  src/components/RecordingIndicator.tsx
  src/types/interview.d.ts
Labels: feature

#56 Dv 209 fe audio presignedurl request
  src/app/mypage/profile/page.tsx
  src/components/fileupload/file-upload-btn.tsx
  src/components/fileupload/file-upload-panel.tsx
  src/components/fileupload/multi-file-upload-panel.tsx
  src/components/interview/step/check-info-step.tsx
  src/components/interview/step/cover-letter-step.tsx
  src/components/interview/step/nav-button.tsx
  src/data/profileData.ts
  src/stores/useFileStore.ts
  src/stores/useInterviewStore.ts
  src/types/interview.d.ts
Labels: feature

#58 [DV-236] 면접 평가지에서 음성/채팅, 기술/인성 면접에 따라 다른 평가기준 적용하기
  src/components/interview/interview-feedback-detail.tsx
  src/components/radar-chart.tsx
  src/constants/evaluationLabels.ts
Labels: refactor, feature

#60 [DV-241] 피드백 관련 수정
  src/app/mypage/feedback/page.tsx
  src/components/EvaluationCriteriaList.tsx
  src/components/interview/interview-feedback-detail.tsx
Labels: refactor

#61 [DV-243] 다양한 이슈 해결
  src/app/interview/ongoing/[interviewId]/page.tsx
  src/components/privacy-policy-modal.tsx
  src/components/term-section.tsx
  src/components/user-form.tsx
  src/data/privacyData.ts
Labels: refactor, feature

#64 Dv 237 fe guide docs
  package.json
  public/firebase-messaging-sw.js
  public/guides/index.md
  src/app/(user)/auth/page.tsx
  src/app/(user)/signup/page.tsx
  src/app/error.tsx
  src/app/error/layout.tsx
  src/app/error/page.tsx
  src/app/guide/page.tsx
  src/app/interview/feedback/[interviewId]/page.tsx
  src/app/interview/ongoing/[interviewId]/page.tsx
  src/app/interview/ongoing/prepare/page.tsx
  src/app/interview/page.tsx
  src/app/layout.tsx
  src/app/mypage/edit/page.tsx
  src/app/mypage/feedback/[interviewId]/page.tsx
  src/app/mypage/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/error/error-boundary.tsx
  src/components/fileupload/file-upload-btn.tsx
  src/components/fileupload/multi-file-upload-panel.tsx
  src/components/guide/guide.tsx
  src/components/header.tsx
  src/components/interview/step/check-info-step.tsx
  src/components/mic-test.tsx
  src/components/modal/custom-modal.tsx
  src/styles/globals.css
Labels: feature

#65 [DV-251] 음성면접 결과지에 나의 답변 재생바 추가하기
  public/audiotest.mp3
  src/components/interview/interview-feedback-detail.tsx
  src/types/interview.d.ts
Labels: refactor, feature

#72 Dv 257 fe update sns and errors
  public/guides/index.md
  src/app/community/page.tsx
  src/app/interview/feedback/[interviewId]/page.tsx
  src/app/interview/ongoing/[interviewId]/page.tsx
  src/app/interview/ongoing/prepare/page.tsx
  src/app/interview/page.tsx
  src/app/mypage/payment-history/page.tsx
  src/components/guide/guide.tsx
  src/components/post-modal.tsx
Labels: feature
