Repository TeamRichardStallman/dv-front, pull requests merged in 2024-11, with the labels that each got.

#5 [DV-53] ProgressBar 컴포넌트 구현하기
  package-lock.json
  package.json
  src/app/interview/page.tsx
  src/app/interview/setup/page.tsx
  src/components/interview/setup-funnel.tsx
  src/components/interview/setup-progress-bar.tsx
  src/components/interview/step/ type-step.tsx
Labels: refactor, feature

#6 [DV-54] SettingBtn 컴포넌트 구현하기
  src/app/interview/page.tsx
  src/components/settingbtn.tsx
Labels: refactor, feature

#7 [DV-58] PositionBtn 컴포넌트 구현하기
  public/ai.png
  public/backend.png
  public/cloud.png
  public/frontend.png
  src/components/interview/step/job-step.tsx
  src/components/interview/step/nav-button.tsx
  src/components/positionbtn.tsx
Labels: feature

#9 DV-66 면접 진행 UI 및 로직 추가
  src/app/api/test/route.ts
  src/app/interview/feedback/loading.tsx
  src/app/interview/feedback/page.tsx
  src/app/interview/ongoing/page.tsx
  src/components/header.tsx
  src/data/questions.ts
  src/data/test.ts
  src/styles/globals.css
  src/types/types.d.ts
  src/utils/format.ts
Labels: feature

#10 DV-18 Kakao oauth 로그인 기능 추가
  package-lock.json
  package.json
  public/kakao_login_large_narrow.png
  src/app/(user)/login/page.tsx
  src/app/(user)/signup/page.tsx
  src/app/api/auth/[...nextauth]/route.js
  src/components/kakao-login-btn.tsx
Labels: feature

#11 [DV-59] 자기소개서 입력 페이지 UI 구현하기
  src/app/interview/layout.tsx
  src/app/interview/setup/page.tsx
  src/components/backbtn.tsx
  src/components/defaultbtn.tsx
  src/components/header.tsx
  src/components/interview/setup-funnel.tsx
  src/components/interview/setup-progress-bar.tsx
  src/components/interview/step/cover-letter-step.tsx
  src/components/interview/step/nav-button.tsx
  src/components/interview/step/type-step.tsx
  src/components/loading.tsx
  src/components/tooltip.tsx
Labels: feature

#12 [DV-60] 면접 setup 페이지 UI 구현
  src/app/interview/layout.tsx
  src/app/interview/page.tsx
  src/app/interview/setup/page.tsx
  src/components/header.tsx
  src/components/interview/step/check-info-step.tsx
  src/components/interview/step/cover-letter-step.tsx
  src/components/interview/step/job-step.tsx
  src/components/interview/step/method-step.tsx
  src/components/interview/step/type-step.tsx
  src/components/settingbtn.tsx
Labels: feature

#13 [DV-65] 세팅버튼 디자인 수정
  src/app/interview/page.tsx
  src/components/interview/step/job-step.tsx
  src/components/interview/step/nav-button.tsx
  src/components/interview/step/type-step.tsx
  src/components/settingbtn.tsx
Labels: refactor, feature

#14 [DV-104] 회원가입 페이지 UI 구현
  public/profile-img.png
  src/app/(user)/consent/page.tsx
  src/app/(user)/signup/page.tsx
  src/components/header.tsx
  src/components/user-form.tsx
Labels: feature

#15 [DV-105] 마이페이지 - 회원정보수정 페이지 UI 구현
  src/app/mypage/edit/page.tsx
  src/app/mypage/layout.tsx
  src/components/description.tsx
  src/components/user-form.tsx
Labels: feature

#16 [DV-106] 마이페이지-나의 취업 정보 페이지 UI 구현
  package-lock.json
  package.json
  public/pdf/자기소개서_1.pdf
  src/app/mypage/profile/page.tsx
Labels: feature

#22 [DV-108] 마이페이지-면접평가확인페이지 UI 구현
  package-lock.json
  package.json
  src/app/mypage/feedback/page.tsx
  src/data/mockInterviewData.ts
Labels: feature

#23 [DV-139] npm start 포트번호 변경
  package.json
  src/app/interview/feedback/page.tsx
Labels: hotfix

#24 [DV-138] 면접 진행 페이지 리팩토링
  src/app/interview/ongoing/page.tsx
Labels: refactor, feature

#25 [DV-140] 마이페이지 내부의 수정사항 반영
  src/app/mypage/feedback/page.tsx
  src/app/mypage/profile/page.tsx
  src/data/mockInterviewData.ts
Labels: refactor, feature

#29 [DV-137] 랜딩페이지 UI 구현
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/footer.tsx
Labels: refactor, feature

#30 [DV-146] hotfix: package.json 내용 추가
  package.json
Labels: hotfix

#35 [DV-158] 디자인 수정 및 자료입력 컴포넌트 기능 추가
  package-lock.json
  package.json
  src/app/interview/page.tsx
  src/components/interview/step/cover-letter-step.tsx
  src/components/interview/step/nav-button.tsx
  src/components/multi-file-upload-panel.tsx
  src/components/settingbtn.tsx
  src/data/profileData.ts
Labels: refactor, feature

#36 [DV-164] 결제로직 관련 UI 구현
  src/app/mypage/coupon/page.tsx
  src/app/mypage/edit/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/payment-history/page.tsx
  src/app/mypage/voucher/page.tsx
Labels: feature

#37 DV-181-fe-payment-api-connection 결제 로직 API 연결
  public/surprised_logo_gray.png
  src/app/mypage/coupon/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/payment-history/page.tsx
  src/app/mypage/voucher/page.tsx
  src/components/no-content.tsx
Labels: feature
