Repository TeamRichardStallman/dv-front, pull requests merged in 2024-10, with the labels that each got.

#1 [DV-78] 컴포넌트 파일 분리
  src/components/backbtn.tsx
  src/components/defaultbtn.tsx
  src/components/description.tsx
  src/components/header.tsx
  src/components/loading.tsx
  src/components/positionbtn.tsx
  src/components/progressbar.tsx
  src/components/settingbtn.tsx
  src/components/tooltip.tsx
  src/components/user-form.tsx
Labels: refactor

#2 DV-87 프론트 베이스 코드 추가
  public/backImage.webp
  src/app/(user)/layout.tsx
  src/app/(user)/login/page.tsx
  src/app/(user)/user/page.tsx
  src/app/interview/feedback/page.tsx
  src/app/interview/layout.tsx
  src/app/interview/ongoing/page.tsx
  src/app/interview/page.tsx
  src/app/interview/setup/page.tsx
  src/app/interviewing/layout.tsx
  src/app/interviewing/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/footer.tsx
  src/components/funnel.tsx
  src/components/header.tsx
  src/components/interview/setup-funnel.tsx
  src/components/interview/setup-progress-bar.tsx
  src/components/interview/step/ type-step.tsx
  src/components/interview/step/check-info-step.tsx
  src/components/interview/step/cover-letter-step.tsx
  src/components/interview/step/job-step.tsx
  src/components/interview/step/method-step.tsx
  src/components/interview/step/nav-button.tsx
  src/components/interview/types.d.ts
  src/components/progress-bar.tsx
  src/components/progressbar.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: refactor, feature

#3 [DV-51] 상단바 구현
  public/backImage.webp
  public/file.svg
  public/globe.svg
  public/logo.png
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/(interview-setting)/coverletter/page.tsx
  src/app/(interview-setting)/format/page.tsx
  src/app/(interview-setting)/mode/page.tsx
  src/app/(interview-setting)/position/page.tsx
  src/app/(interview-setting)/type/page.tsx
  src/app/(interviewing)/feedback-waiting/page.tsx
  src/app/(interviewing)/interview-waiting/page.tsx
  src/app/(interviewing)/interview-warning/page.tsx
  src/app/(interviewing)/interview/[[...id]].tsx/page.tsx
  src/app/(interviewing)/setting-check.tsx/page.tsx
  src/app/(user)/user/page.tsx
  src/app/fonts/GeistMonoVF.woff
  src/app/fonts/GeistVF.woff
  src/app/fonts/Pretendard-Black.woff2
  src/app/fonts/Pretendard-Bold.woff2
  src/app/fonts/Pretendard-ExtraBold.woff2
  src/app/fonts/Pretendard-ExtraLight.woff2
  src/app/fonts/Pretendard-Light.woff2
  src/app/fonts/Pretendard-Medium.woff2
  src/app/fonts/Pretendard-Regular.woff2
  src/app/fonts/Pretendard-SemiBold.woff2
  src/app/fonts/Pretendard-Thin.woff2
  src/app/interviewing/layout.tsx
  src/app/interviewing/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/header.tsx
  src/components/interview/setup-progress-bar.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: refactor, feature

#4 DV-90 pr, issue template 추가
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation
